name: Tech Ambassadors
favicon: null
layout_spectrum: 0.7967022601515055
typography_spectrum: 0.11291608726605773
title: Tech Ambassadors Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#d62531'
    - '#ffffff'
    - '#8c8c8c'
    - '#646463'
  brandStrength: 1
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
